function stability = assessOptimisedResultStability(result)
%ASSESSOPTIMISEDRESULTSTABILITY Check the fitted physical network.

tolerance = 1e-9;

physicalParametersPositive = ...
    result.Rline >= 0 && ...
    result.Gline >= 0 && ...
    result.Lline > 0 && ...
    result.Cline > 0 && ...
    result.Rr >= 0 && ...
    result.Lr >= 0 && ...
    result.Rcr >= 0 && ...
    result.Cr > 0;

if result.Rcr > 0
    remainingPoles = -1/(result.Rcr*result.Cr);
else
    remainingPoles = [];
end

remainingPoleStable = ...
    isempty(remainingPoles) || all(real(remainingPoles) < 0);

minRealGamma = min(real(result.gamma));
maxAbsH = max(abs(result.H));

linePropagationPassive = ...
    minRealGamma >= -tolerance && ...
    maxAbsH <= 1 + tolerance;

stability = struct();
stability.physicalParametersPositive = physicalParametersPositive;
stability.remainingPoles = remainingPoles;
stability.remainingPoleStable = remainingPoleStable;
stability.minRealGamma = minRealGamma;
stability.maxAbsH = maxAbsH;
stability.linePropagationPassive = linePropagationPassive;
stability.isStable = ...
    physicalParametersPositive && ...
    remainingPoleStable && ...
    linePropagationPassive;
end


