function interface = loadOptimisedTlmInterfaceResult(saveFile)
%LOADOPTIMISEDTLMINTERFACERESULT Load saved Heaviside optimisation outputs.
%
% The LCTLM Simulink models should not rerun the optimisation in InitFcn.
% They load the result generated by heaviside_line_equivalent_optimise.m.

if exist(saveFile, 'file') ~= 2
    error(['Optimised TLM interface file was not found:\n%s\n', ...
        'Run heaviside_line_equivalent_optimise.m first.'], saveFile);
end

savedData = load(saveFile, 'result', 'filterResult');

if ~isfield(savedData, 'result') || ~isfield(savedData, 'filterResult')
    error(['Optimised TLM interface file must contain variables ', ...
        '"result" and "filterResult":\n%s'], saveFile);
end

result = savedData.result;
filterResult = savedData.filterResult;

requireFields(result, {'Zinf', 'Rr', 'Lr', 'Rcr', 'Cr', 'tau'}, 'result');
requireFields(filterResult, ...
    {'bZc', 'aZc', 'bHr', 'aHr', 'bHrLowPass', 'aHrLowPass', ...
    'Ts', 'tau', 'stability'}, ...
    'filterResult');

if isfield(result, 'stability') && ~result.stability.isStable
    error('The saved optimised physical line result is marked unstable.');
end

if isfield(filterResult.stability, 'isStable') && ...
        ~filterResult.stability.isStable
    error('The saved optimised filter result is marked unstable.');
end

if isfield(filterResult.stability, 'zcStrictlyCausal') && ...
        ~filterResult.stability.zcStrictlyCausal
    error('The saved Zc filter is not strictly causal.');
end

if ~isfield(filterResult, 'zcFitQuantity') || ...
        ~strcmp(filterResult.zcFitQuantity, ...
        'Zc_residual_ohm_plus_base_RL')
    error(['The saved Zc filter is not the residual-plus-base-RL form ', ...
        'expected by the current LCTLM setup. Run ', ...
        'heaviside_line_equivalent_optimise.m again.']);
end

line_bZc = normaliseRow(filterResult.bZc);
line_aZc = normaliseRow(filterResult.aZc);
line_bHr = normaliseRow(filterResult.bHr);
line_aHr = normaliseRow(filterResult.aHr);
hr_lp_b = normaliseRow(filterResult.bHrLowPass);
hr_lp_a = normaliseRow(filterResult.aHrLowPass);

if abs(line_bZc(1)) > 0
    error(['The saved residual Zc filter has direct feedthrough: ', ...
        'bZc(1) = %.12e.'], ...
        line_bZc(1));
end

if any(abs(roots(line_aZc)) >= 1)
    error('The saved discrete residual Zc filter is unstable.');
end

if any(abs(roots(line_aHr)) >= 1)
    error('The saved discrete Hr filter is unstable.');
end

if any(abs(roots(hr_lp_a)) >= 1)
    error('The saved discrete Hr low-pass filter is unstable.');
end

interface = struct();
interface.Z_inf = result.Zinf;
interface.Rsum = result.Rr;
interface.Lsun = result.Lr;
interface.Lsum = result.Lr;
interface.C_remain = result.Cr;
interface.R_remain = result.Rcr;
interface.R_remain_client = readRemainder(result, 'client', 'R');
interface.L_remain_client = readRemainder(result, 'client', 'L');
interface.R_remain_server = readRemainder(result, 'server', 'R');
interface.L_remain_server = readRemainder(result, 'server', 'L');
interface.Zc_base_R = readRequiredField(filterResult, 'ZcBaseR');
interface.Zc_base_L = readRequiredField(filterResult, 'ZcBaseL');
interface.line_bZc = line_bZc;
interface.line_aZc = line_aZc;
interface.line_bHr = line_bHr;
interface.line_aHr = line_aHr;
interface.hr_lp_b = hr_lp_b;
interface.hr_lp_a = hr_lp_a;
interface.line_sampleTime = filterResult.Ts;
interface.line_fixedDelay = filterResult.tau;
interface.sourceFile = saveFile;
end


function value = readRemainder(result, sideName, quantityName)
fieldName = ['R_remain_', sideName];

if strcmp(quantityName, 'L')
    fieldName = ['L_remain_', sideName];
end

if isfield(result, fieldName)
    value = result.(fieldName);
    return;
end

if ~isfield(result, 'separatedSeries')
    error('Missing result.separatedSeries in saved optimisation result.');
end

if strcmp(sideName, 'client')
    terminalName = 'terminal1';
else
    terminalName = 'terminal2';
end

if ~isfield(result.separatedSeries, terminalName) || ...
        ~isfield(result.separatedSeries.(terminalName), quantityName)
    error('Missing result.separatedSeries.%s.%s.', ...
        terminalName, quantityName);
end

value = result.separatedSeries.(terminalName).(quantityName);
end


function value = readRequiredField(valueStruct, fieldName)

if ~isfield(valueStruct, fieldName)
    error('Missing required field filterResult.%s.', fieldName);
end

value = valueStruct.(fieldName);
end


function requireFields(value, names, ownerName)
for k = 1:numel(names)
    if ~isfield(value, names{k})
        error('Missing field %s.%s in saved optimisation result.', ...
            ownerName, names{k});
    end
end
end


function row = normaliseRow(value)
row = value(:).';

if isempty(row) || any(~isfinite(row))
    error('Saved filter coefficient vector is empty or non-finite.');
end
end
