function plotResult(result)

f = result.frequency;
nFrequency = numel(f);

T0n      = complex(zeros(4,nFrequency));
Tnewn    = complex(zeros(4,nFrequency));
Tdirectn = complex(zeros(4,nFrequency));

for k = 1:nFrequency
    T0 = normaliseABCD( ...
        result.Toriginal(:,:,k), result.Zbase);

    Tn = normaliseABCD( ...
        result.Tnew(:,:,k), result.Zbase);

    Td = normaliseABCD( ...
        result.TdirectBaseline(:,:,k), result.Zbase);

    T0n(:,k)      = T0(:);
    Tnewn(:,k)    = Tn(:);
    Tdirectn(:,k) = Td(:);
end

% MATLAB column ordering: A, C, B, D
labels = {'A', 'CZ_b', 'B/Z_b', 'D'};

figure('Name','ABCD magnitude comparison');

for k = 1:4
    subplot(2,2,k);

    semilogx( ...
        f, ...
        20*log10(max(abs(T0n(k,:)),eps)), ...
        'LineWidth',1.3);

    hold on;

    semilogx( ...
        f, ...
        20*log10(max(abs(Tnewn(k,:)),eps)), ...
        '--', ...
        'LineWidth',1.3);

    semilogx( ...
        f, ...
        20*log10(max(abs(Tdirectn(k,:)),eps)), ...
        ':', ...
        'LineWidth',1.5);

    grid on;
    xlabel('Frequency (Hz)');
    ylabel('Magnitude (dB)');
    title(labels{k});

    if k == 1
        legend( ...
            'Original RL--RC network', ...
            'Optimised line + remaining network', ...
            'Original RL--RC + direct delay', ...
            'Location','best');
    end
end

figure('Name','ABCD phase comparison');

for k = 1:4
    subplot(2,2,k);

    semilogx( ...
        f, ...
        unwrap(angle(T0n(k,:)))*180/pi, ...
        'LineWidth',1.3);

    hold on;

    semilogx( ...
        f, ...
        unwrap(angle(Tnewn(k,:)))*180/pi, ...
        '--', ...
        'LineWidth',1.3);

    semilogx( ...
        f, ...
        unwrap(angle(Tdirectn(k,:)))*180/pi, ...
        ':', ...
        'LineWidth',1.5);

    grid on;
    xlabel('Frequency (Hz)');
    ylabel('Phase (deg)');
    title(labels{k});

    if k == 1
        legend( ...
            'Original RL--RC network', ...
            'Optimised line + remaining network', ...
            'Original RL--RC + direct delay', ...
            'Location','best');
    end
end

figure('Name','Two-port fitting error comparison');

loglog( ...
    f, ...
    max(result.relativeError,eps), ...
    'LineWidth',1.4);

hold on;

loglog( ...
    f, ...
    max(result.directRelativeError,eps), ...
    '--', ...
    'LineWidth',1.4);

grid on;
xlabel('Frequency (Hz)');
ylabel('Relative normalised ABCD error');
title('Optimised reconstruction versus original RL-RC with direct delay');

legend( ...
    'Optimised line + remaining network', ...
    'Original RL--RC + direct delay', ...
    'Location','best');

figure('Name','Equivalent transmission-line quantities');

subplot(2,1,1);

semilogx( ...
    f, ...
    abs(result.Zc), ...
    'LineWidth',1.3);

grid on;
xlabel('Frequency (Hz)');
ylabel('|Z_c| (\Omega)');
title('Characteristic impedance');

subplot(2,1,2);

semilogx( ...
    f, ...
    unwrap(angle(result.H))*180/pi, ...
    'LineWidth',1.3);

grid on;
xlabel('Frequency (Hz)');
ylabel('Phase of H (deg)');
title('Propagation function');

end


